_editables:
  content:
    bold: true
    italic: true
    bulletedlist: true
    numberedlist: true
    image: true
    table: true
    undo: true
    redo: true

_inputs:
  background:
    type: color
    comment: Defines the background for the entire page
  hero_content:
    type: markdown
    label: Hero text
  sidebar:
    type: checkbox
    hidden: true

