# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Counter
  description: Counter section
  icon: "functions"
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  title: "Title with a"
  title_suffix: "Keyword"
  description: Enter your description text here.
  alternate_style: false
  numbers:
    - prefix: "$"
      number: 300
      suffix: "m"
      text: "Venture capital raised"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description:
    type: markdown
